development:
  adapter: postgresql
  encoding: unicode
  database: second_oath_development
  pool: 2

production:
  adapter: postgresql
  encoding: unicode
  database: second_oath_production
  pool: 2
